apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: ratheeshkanth/spring-boot-mango
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
    
-----
apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mango
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
         volumeMounts:
         - name: mongo-pvc
           mountPath: /data/db
        volumes:
       - name: mongo-pvc
         hostPath:
          path: /tmp/dbbackup
-----
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
